version: '3'
services:
  hadoop-master:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    hostname: hadoop-master
    ports:
      - "50070:50070"
    networks:
      - hadoop-net

  hadoop-worker1:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    hostname: hadoop-worker1
    networks:
      - hadoop-net

  hadoop-worker2:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    hostname: hadoop-worker2
    networks:
      - hadoop-net

  hadoop-worker3:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    hostname: hadoop-worker3
    networks:
      - hadoop-net

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    hostname: spark-worker
    depends_on:
      - hadoop-master
    networks:
      - hadoop-net

networks:
  hadoop-net:
